/*
===================================================
PROYECTO     : Quiniela de deportes                     
BASE DATOS   : PROYECTO
MOTOR        : SQL Server 2022
===================================================
*/

-- EVENTO
CREATE INDEX IX_EVENTO_APUESTA
    ON EVENTO (ID_APUESTA)
    INCLUDE (NOMBRE, FECHA);
GO

-- PRONOSTICO
CREATE INDEX IX_PRONOSTICO_EVENTO_USUARIO
    ON PRONOSTICO (ID_EVENTO, ID_USUARIO)
    INCLUDE (PTS_LOCAL, PTS_VISITANTE, ID_PRONOSTICO);
GO

-- USUARIO_APUESTA
CREATE INDEX IX_UA_APUESTA_USUARIO
    ON USUARIO_APUESTA (ID_APUESTA, ID_USUARIO)
    INCLUDE (PUNTOS);
GO

-- Índice inverso para búsquedas por usuario (ranking global, historial)
CREATE INDEX IX_UA_USUARIO_APUESTA
    ON USUARIO_APUESTA (ID_USUARIO)
    INCLUDE (ID_APUESTA, PUNTOS);
GO

-- EVENTO_RESULTADO
CREATE INDEX IX_EVRES_EVENTO
    ON EVENTO_RESULTADO (ID_EVENTO)
    INCLUDE (RESULTADO, PTS_EQUIPO_A, PTS_EQUIPO_B);
GO

-- APUESTA
CREATE INDEX IX_APUESTA_ESTADO
    ON APUESTA (ID_ESTADO_APUESTA)
    INCLUDE (NOMBRE, FECHA_INICIO, FECHA_FIN, ID_TIPO_PUNTUACION, DESCRIPCION);
GO

-- ESTADO_USUARIO
CREATE INDEX IX_ESTADOUSER_USUARIO
    ON ESTADO_USUARIO (ID_USUARIO)
    INCLUDE (ROL, ESTADO);
GO

-- HISTORIAL_PUNTOS
CREATE INDEX IX_HP_USUARIO
    ON HISTORIAL_PUNTOS (ID_USUARIO)
    INCLUDE (ID_APUESTA, ID_PRONOSTICO);
GO

CREATE INDEX IX_HP_APUESTA
    ON HISTORIAL_PUNTOS (ID_APUESTA);
GO

CREATE INDEX IX_HP_PRONOSTICO
    ON HISTORIAL_PUNTOS (ID_PRONOSTICO);
GO
