/*
===================================================
PROYECTO     : Quiniela de deportes                     
BASE DATOS   : PROYECTO
MOTOR        : SQL Server 2022
===================================================
*/

-- Borrar si existe
DROP DATABASE IF EXISTS PROYECTO;
GO

-- Crear la DB
CREATE DATABASE PROYECTO;
GO 

-- Configuración de la DB
ALTER DATABASE PROYECTO SET RECOVERY FULL; -- Habilita backups de log de transacciones
ALTER DATABASE PROYECTO SET AUTO_CLOSE OFF; -- Mantiene la BD en memoria siempre activa
ALTER DATABASE PROYECTO SET AUTO_SHRINK OFF; -- Evita reducción automática del archivo de datos
GO

USE PROYECTO;
GO

-- Crar usuario para la conexion SQL Authentication e ingreso
-- a la DB con permisos de administrador.
CREATE LOGIN [admin] WITH PASSWORD = 'root';
CHECK_POLICY = OFF;
CHECK_EXPIRATION = OFF;
GO

CREATE USER [admin] FOR LOGIN [admin];
GO

ALTER ROLE db_owner ADD MEMBER [admin];
GO

-- Datos personales base de cualquier individuo, sea usuario o atleta.
DROP TABLE IF EXISTS PERSONA;
GO
CREATE TABLE PERSONA
(
    ID_PERSONA          INT IDENTITY(1,1) PRIMARY KEY,
    PRIMER_NOMBRE       VARCHAR(20)       NOT NULL,
    SEGUNDO_NOMBRE      VARCHAR(20)       NULL,
    PRIMER_APELLIDO     VARCHAR(20)       NOT NULL,
    SEGUNDO_APELLIDO    VARCHAR(20)       NULL,
    FECHA_NACIMIENTO    DATE              NOT NULL --yy/mm/dd
);
GO

-- Credenciales de acceso. Cada usuario está vinculado a una unica persona.
DROP TABLE IF EXISTS USUARIO;
GO
CREATE TABLE USUARIO
(
    ID_USUARIO          INT IDENTITY(1,1) PRIMARY KEY,
    ID_PERSONA          INT               UNIQUE NOT NULL, 
    CORREO_ELECTRONICO  VARCHAR(100)      UNIQUE NOT NULL,
    USERNAME            VARCHAR(50)       UNIQUE NOT NULL,
    PASS                VARCHAR(255)      NOT NULL, -- hash
   
    CONSTRAINT FK_PERSONA_USUARIO
    FOREIGN KEY (ID_PERSONA)
    REFERENCES PERSONA(ID_PERSONA)
);
GO

-- Historial de rol y estado por usuario.
DROP TABLE IF EXISTS ESTADO_USUARIO;
GO
CREATE TABLE ESTADO_USUARIO
(
    ID_ESTADO_USUARIO   INT IDENTITY(1,1) PRIMARY KEY,
    ID_USUARIO          INT               NOT NULL, 
    ROL                 VARCHAR(10)       NOT NULL,
    ESTADO              VARCHAR(20)       NOT NULL,

    CONSTRAINT FK_ESTADO_USUARIO
    FOREIGN KEY (ID_USUARIO)
    REFERENCES USUARIO(ID_USUARIO),

    CONSTRAINT CK_ROL CHECK (ROL IN ('ADMIN', 'JUGADOR')),
    
    CONSTRAINT CK_ESTADOUSER CHECK ( ESTADO IN (
        'PENDIENTE', 'APROBADO', 'RECHAZADO','SUSPENDIDO') 
    )
);
GO

-- Selecciones nacionales participantes en Copa del Mundo 2026.
DROP TABLE IF EXISTS EQUIPO;
GO
CREATE TABLE EQUIPO
(
    ID_EQUIPO  INT IDENTITY(1,1) PRIMARY KEY,
    NOMBRE     VARCHAR(50)       UNIQUE NOT NULL
);
GO

-- Ciclo de vida de una apuesta
DROP TABLE IF EXISTS ESTADO_APUESTA;
GO
CREATE TABLE ESTADO_APUESTA
(
    ID_ESTADO_APUESTA INT IDENTITY(1,1) PRIMARY KEY,
    NOMBRE VARCHAR(10) UNIQUE NOT NULL,

    CONSTRAINT CK_ESTADO_APUESTA 
    CHECK (NOMBRE IN ('CREADA','ABIERTA','CERRADA','FINALIZADA'))
);
GO

--  Base para la puntuacion de una apuesta
DROP TABLE IF EXISTS TIPO_PUNTUACION;
GO
CREATE TABLE TIPO_PUNTUACION 
(
    ID_TIPO_PUNTUACION INT IDENTITY(1,1) PRIMARY KEY,
    NOMBRE             VARCHAR(100)      UNIQUE NOT NULL,
    PUNTOS_BASE        DECIMAL(5,2)      NOT NULL DEFAULT 1.00,
    MULTIPLICADOR      DECIMAL(5,2)      NOT NULL DEFAULT 1.00,
    PENALIZACION       DECIMAL(5,2)      NOT NULL DEFAULT 0.00
);
GO

-- Apuesta principal. Agrupa eventos bajo nombre, reglas, fechas
-- y tipo de puntuacion.
DROP TABLE IF EXISTS APUESTA;
GO
CREATE TABLE APUESTA
(
    ID_APUESTA          INT IDENTITY(1,1) PRIMARY KEY,
    ID_ESTADO_APUESTA   INT               NOT NULL,
    ID_TIPO_PUNTUACION  INT               NOT NULL,
    NOMBRE              VARCHAR(100)      UNIQUE NOT NULL,
    DESCRIPCION         VARCHAR(500)      NOT NULL,
    REGLAS              VARCHAR(500)      NOT NULL,
    FECHA_INICIO        DATETIME2         NOT NULL,
    FECHA_FIN           DATETIME2         NOT NULL,

    CONSTRAINT FK_APUESTA_ESTADO
    FOREIGN KEY (ID_ESTADO_APUESTA)
    REFERENCES ESTADO_APUESTA(ID_ESTADO_APUESTA),

    CONSTRAINT FK_APUESTA_TIPO_PUNT
    FOREIGN KEY (ID_TIPO_PUNTUACION)
    REFERENCES TIPO_PUNTUACION(ID_TIPO_PUNTUACION),

    CONSTRAINT CK_FECHAS CHECK (FECHA_FIN > FECHA_INICIO)
);
GO

-- Evento individual dentro de una apuesta. Es lo que el jugador debe predecir.
DROP TABLE IF EXISTS EVENTO;
GO
CREATE TABLE EVENTO
(
    ID_EVENTO       INT IDENTITY(1,1) PRIMARY KEY,
    ID_APUESTA      INT               NOT NULL,
    NOMBRE          VARCHAR(100)      NOT NULL,
    FECHA           DATETIME2         NOT NULL,
    
    CONSTRAINT FK_EVENTO_APUESTA
    FOREIGN KEY (ID_APUESTA)
    REFERENCES APUESTA(ID_APUESTA)
);
GO

-- Resultado oficial de un evento. Se usa para evaluar pronosticos al cerrar.
DROP TABLE IF EXISTS EVENTO_RESULTADO;
GO
CREATE TABLE EVENTO_RESULTADO
(
    ID_EVENTO_RESULTADO INT IDENTITY(1,1) PRIMARY KEY,
    ID_EVENTO           INT               NOT NULL UNIQUE,
    RESULTADO           VARCHAR(100)      NOT NULL,
    PTS_EQUIPO_A        INT,
    PTS_EQUIPO_B        INT,
    FECHA_REGISTRO      DATETIME2 DEFAULT SYSDATETIME(),

    CONSTRAINT FK_EVRES_EVENTO
    FOREIGN KEY (ID_EVENTO)
    REFERENCES EVENTO(ID_EVENTO)
);
GO

-- RELACIÓN USUARIO - APUESTA (participación + puntos)
DROP TABLE IF EXISTS USUARIO_APUESTA;
GO
CREATE TABLE USUARIO_APUESTA
(
    ID_USUARIO  INT NOT NULL,
    ID_APUESTA  INT NOT NULL,
    PUNTOS      DECIMAL(10,2) DEFAULT 0,

    PRIMARY KEY (ID_USUARIO, ID_APUESTA),

    CONSTRAINT FK_UA_USUARIO
    FOREIGN KEY (ID_USUARIO)
    REFERENCES USUARIO(ID_USUARIO),

    CONSTRAINT FK_UA_APUESTA
    FOREIGN KEY (ID_APUESTA)
    REFERENCES APUESTA(ID_APUESTA)
);
GO

-- PRONÓSTICO (lo que predice el usuario: marcador local y visitante)
DROP TABLE IF EXISTS PRONOSTICO;
GO
CREATE TABLE PRONOSTICO
(
    ID_PRONOSTICO  INT IDENTITY(1,1) PRIMARY KEY,
    ID_USUARIO     INT NOT NULL,
    ID_EVENTO      INT NOT NULL,

    PTS_LOCAL      INT NOT NULL DEFAULT 0,
    PTS_VISITANTE  INT NOT NULL DEFAULT 0,
    FECHA_REGISTRO DATETIME2 DEFAULT SYSDATETIME(),

    CONSTRAINT UQ_PRONOSTICO UNIQUE (ID_USUARIO, ID_EVENTO),

    CONSTRAINT FK_PRON_USUARIO
    FOREIGN KEY (ID_USUARIO)
    REFERENCES USUARIO(ID_USUARIO),

    CONSTRAINT FK_PRON_EVENTO
    FOREIGN KEY (ID_EVENTO)
    REFERENCES EVENTO(ID_EVENTO)
);
GO

-- Catálogo de premios canjeables por puntos.

DROP TABLE IF EXISTS PREMIO;
GO
CREATE TABLE PREMIO
(
    ID_PREMIO       INT IDENTITY(1,1) PRIMARY KEY,
    NOMBRE          VARCHAR(100)      NOT NULL,
    DESCRIPCION     VARCHAR(500)      NOT NULL,
    COSTO_PUNTOS    INT               NOT NULL,
    STOCK           INT               NULL,        -- NULL = ilimitado
    ACTIVO          BIT               NOT NULL DEFAULT 1,
    FECHA_INICIO    DATE              NULL,
    FECHA_FIN       DATE              NULL,
    IMAGEN_URL      VARCHAR(500)      NULL,

    CONSTRAINT CK_COSTO_PUNTOS CHECK (COSTO_PUNTOS > 0)
);
GO

-- Registro de canjes realizados por los jugadores.
DROP TABLE IF EXISTS CANJE;
GO
CREATE TABLE CANJE
(
    ID_CANJE        INT IDENTITY(1,1) PRIMARY KEY,
    ID_USUARIO      INT               NOT NULL,
    ID_PREMIO       INT               NOT NULL,
    PUNTOS_USADOS   INT               NOT NULL,
    FECHA_CANJE     DATETIME2         DEFAULT SYSDATETIME(),
    ESTADO          VARCHAR(20)       NOT NULL DEFAULT 'PENDIENTE',

    CONSTRAINT FK_CANJE_USUARIO
    FOREIGN KEY (ID_USUARIO)
    REFERENCES USUARIO(ID_USUARIO),

    CONSTRAINT FK_CANJE_PREMIO
    FOREIGN KEY (ID_PREMIO)
    REFERENCES PREMIO(ID_PREMIO),

    CONSTRAINT CK_ESTADO_CANJE
    CHECK (ESTADO IN ('PENDIENTE','ENTREGADO','RECHAZADO'))
);
GO

--  Detalle de cada movimiento de puntos por pronóstico evaluado.
DROP TABLE IF EXISTS HISTORIAL_PUNTOS;
GO
CREATE TABLE HISTORIAL_PUNTOS
(
    ID_HISTORIAL    INT IDENTITY(1,1) PRIMARY KEY,
    ID_USUARIO      INT           NOT NULL,
    ID_APUESTA      INT           NOT NULL,
    ID_PRONOSTICO   INT           NOT NULL,
    PUNTOS          DECIMAL(10,2) NOT NULL,
    FECHA_REGISTRO  DATETIME2 DEFAULT SYSDATETIME(),

    CONSTRAINT FK_HP_USUARIO
    FOREIGN KEY (ID_USUARIO)
    REFERENCES USUARIO(ID_USUARIO),

    CONSTRAINT FK_HP_APUESTA
    FOREIGN KEY (ID_APUESTA)
    REFERENCES APUESTA(ID_APUESTA),

    CONSTRAINT FK_HP_PRONOSTICO
    FOREIGN KEY (ID_PRONOSTICO)
    REFERENCES PRONOSTICO(ID_PRONOSTICO)
);
GO