export const ESTADO_APUESTA = {
    CREADA: 1,
    ABIERTA: 2,
    CERRADA: 3,
    FINALIZADA: 4,
};

export const ESTADO_USUARIO = {
    PENDIENTE: 'PENDIENTE',
    APROBADO: 'APROBADO',
    RECHAZADO: 'RECHAZADO',
    SUSPENDIDO: 'SUSPENDIDO',
};

export const ESTADO_CANJE = {
    PENDIENTE: 'PENDIENTE',
    ENTREGADO: 'ENTREGADO',
    RECHAZADO: 'RECHAZADO',
};
